/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JNIWrapper */

#ifndef _Included_jni_JNIWrapper
#define _Included_jni_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JNIWrapper
 * Method:    resqueSPJ
 * Signature: ([Ljava/lang/String;III)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jni_JNIWrapper_resqueSPJ
  (JNIEnv *, jclass, jobjectArray, jint, jint, jint);

/*
 * Class:     jni_JNIWrapper
 * Method:    resqueTileDice
 * Signature: ([Ljava/lang/String;III)D
 */
JNIEXPORT jdouble JNICALL Java_jni_JNIWrapper_resqueTileDice
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint);

/*
 * Class:     jni_JNIWrapper
 * Method:    resqueKNN
 * Signature: ([Ljava/lang/String;IIII)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jni_JNIWrapper_resqueKNN
  (JNIEnv *, jclass, jobjectArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
