/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JNIWrapper */

#ifndef _Included_jni_JNIWrapper
#define _Included_jni_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JNIWrapper
 * Method:    resque
 * Signature: ([Ljava/lang/String;Ljava/lang/String;II)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jni_JNIWrapper_resque
  (JNIEnv *, jclass, jobjectArray, jstring, jint, jint);

/*
 * Class:     jni_JNIWrapper
 * Method:    resqueTileDice
 * Signature: ([Ljava/lang/String;Ljava/lang/String;II)D
 */
JNIEXPORT jdouble JNICALL Java_jni_JNIWrapper_resqueTileDice
  (JNIEnv *, jobject, jobjectArray, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
